package org.fractalx.admin.services;

import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Tracks per-service deployment stage history.
 * Pre-seeded at startup with the initial generation record.
 * New deployment records can be appended at runtime via {@link #addRecord}.
 */
@Component
public class DeploymentTracker {

    public enum StageStatus { PENDING, IN_PROGRESS, DONE, FAILED }

    public record DeploymentStage(
            String name, StageStatus status, String timestamp, long durationMs) {}

    public record DeploymentRecord(
            String service, String version, String deployedAt,
            List<DeploymentStage> stages, String triggeredBy) {}

    private final Map<String, List<DeploymentRecord>> history = new ConcurrentHashMap<>();

    @PostConstruct
    public void init() {
        addInitialRecord("department-service");
        addInitialRecord("employee-service");
        addInitialRecord("leave-service");
        addInitialRecord("payroll-service");
        addInitialRecord("recruitment-service");
        addInitialRecord("fractalx-saga-orchestrator");
        addInitialRecord("fractalx-registry");
        addInitialRecord("api-gateway");
        addInitialRecord("admin-service");
        addInitialRecord("logger-service");
    }

    public void addRecord(DeploymentRecord record) {
        history.computeIfAbsent(record.service(), k -> new CopyOnWriteArrayList<>())
               .add(record);
    }

    public DeploymentRecord getLatest(String service) {
        List<DeploymentRecord> records = history.getOrDefault(service, List.of());
        return records.isEmpty() ? null : records.get(records.size() - 1);
    }

    public List<DeploymentRecord> getHistory(String service) {
        return new ArrayList<>(history.getOrDefault(service, List.of()));
    }

    public Map<String, List<DeploymentRecord>> getAllHistory() {
        return Map.copyOf(history);
    }

    private void addInitialRecord(String service) {
        List<DeploymentStage> stages = List.of(
            new DeploymentStage("BUILD",   StageStatus.DONE, "Initial generation", 0L),
            new DeploymentStage("PACKAGE", StageStatus.DONE, "Initial generation", 0L),
            new DeploymentStage("DEPLOY",  StageStatus.DONE, "Initial generation", 0L)
        );
        addRecord(new DeploymentRecord(
            service, "1.0.0", "Generated by FractalX v0.2.3",
            stages, "FractalX Generator"));
    }
}
