-- ============================================================
-- FractalX Generated Migration — leave-service
-- V1: Initial schema
--
-- IMPORTANT: Review and adjust column types, constraints, and
-- indexes before running in production. This is a scaffold only.
-- Set spring.jpa.hibernate.ddl-auto=validate for production.
-- ============================================================

-- Table: leave_entries (from LeaveEntry)
CREATE TABLE IF NOT EXISTS leave_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT,
    leave_type VARCHAR(255),
    start_date DATE,
    end_date DATE,
    leave_days INT,
    reason VARCHAR(255),
    status VARCHAR(255),
    requested_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Transactional outbox table (FractalX event publishing)
CREATE TABLE IF NOT EXISTS fractalx_outbox (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_type  VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    payload     TEXT,
    published   BOOLEAN NOT NULL DEFAULT FALSE,
    retry_count INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL,
    published_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON fractalx_outbox (published, created_at);
