package com.example.hr.leave;

import org.fractalx.netscope.client.annotation.NetScopeClient;
import com.example.hr.employee.Employee;
import java.math.BigDecimal;
import java.util.List;

/**
 * NetScope client interface for EmployeeService.
 * Connects to employee-service on gRPC port 18081.
 * Generated by FractalX Framework.
 */
@NetScopeClient(server = "employee-service", beanName = "EmployeeService")
public interface EmployeeServiceClient {

    void markOnLeave(Long employeeId);

    void cancelMarkOnLeave(Long employeeId);

    Employee createEmployee(String firstName, String lastName, String email, String position, BigDecimal salary, Long departmentId);

    void cancelCreateEmployee(String firstName, String lastName, String email, String position, BigDecimal salary, Long departmentId);

    Employee findById(Long id);

    boolean exists(Long id);

    void terminate(Long employeeId);

    List<Employee> findByDepartment(Long departmentId);

    List<Employee> findActive();

}
