package com.example.hr.recruitment;

import org.fractalx.netscope.client.annotation.NetScopeClient;
import com.example.hr.department.Department;

/**
 * NetScope client interface for DepartmentService.
 * Connects to department-service on gRPC port 18085.
 * Generated by FractalX Framework.
 */
@NetScopeClient(server = "department-service", beanName = "DepartmentService")
public interface DepartmentServiceClient {

    void assignToDepartment(Long employeeId, Long departmentId);

    void cancelAssignToDepartment(Long employeeId, Long departmentId);

    void incrementHeadcount(Long departmentId);

    void cancelIncrementHeadcount(Long departmentId);

    Department findById(Long id);

    boolean exists(Long id);

    Department createDepartment(String code, String name, java.math.BigDecimal budget);

    java.util.List<Department> findAllActive();

}
