package com.example.hr.employee;

import org.fractalx.netscope.client.annotation.NetScopeClient;
import com.example.hr.payroll.PayrollRecord;
import java.math.BigDecimal;
import java.util.List;

/**
 * NetScope client interface for PayrollService.
 * Connects to payroll-service on gRPC port 18082.
 * Generated by FractalX Framework.
 */
@NetScopeClient(server = "payroll-service", beanName = "PayrollService")
public interface PayrollServiceClient {

    PayrollRecord setupPayroll(Long employeeId, BigDecimal salary);

    void cancelSetupPayroll(Long employeeId, BigDecimal salary);

    void deductLeave(Long employeeId, Integer leaveDays);

    void cancelDeductLeave(Long employeeId, Integer leaveDays);

    List<PayrollRecord> findByEmployee(Long employeeId);

    List<PayrollRecord> findByPeriod(Integer year, Integer month);

}
