-- ============================================================
-- FractalX Generated Migration — recruitment-service
-- V1: Initial schema
--
-- IMPORTANT: Review and adjust column types, constraints, and
-- indexes before running in production. This is a scaffold only.
-- Set spring.jpa.hibernate.ddl-auto=validate for production.
-- ============================================================

-- Table: candidates (from Candidate)
CREATE TABLE IF NOT EXISTS candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    applied_position VARCHAR(255),
    target_department_id BIGINT,
    offered_salary DECIMAL(19,4),
    application_status VARCHAR(255),
    applied_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Transactional outbox table (FractalX event publishing)
CREATE TABLE IF NOT EXISTS fractalx_outbox (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_type  VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    payload     TEXT,
    published   BOOLEAN NOT NULL DEFAULT FALSE,
    retry_count INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP NOT NULL,
    published_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON fractalx_outbox (published, created_at);
