package org.fractalx.gateway;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * FractalX API Gateway - Auto-generated by FractalX Framework
 */
@SpringBootApplication
public class FractalXGatewayApplication {

    public static void main(String[] args) {
        SpringApplication.run(FractalXGatewayApplication.class, args);
    }
}
